"""adiciona_gestao_de_caixa_pdv

Revision ID: 1ebae9a8da28
Revises: 9021d6be7b2d
Create Date: 2025-10-01 08:51:38.735093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ebae9a8da28'
down_revision: Union[str, Sequence[str], None] = '9021d6be7b2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
