"""Adiciona paid_quantity e corrige schemas

Revision ID: 3f7dfee389f1
Revises: a08d007466c4
Create Date: 2025-10-17 18:55:16.249328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f7dfee389f1'
down_revision: Union[str, Sequence[str], None] = 'a08d007466c4' # Verifique se o ID anterior está correto
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # --- INÍCIO DA CORREÇÃO ---
    # Adicionamos server_default='0' para que o banco de dados saiba
    # o que colocar nas linhas que já existem.
    op.add_column('order_items', sa.Column('paid_quantity', sa.Integer(), nullable=False, server_default='0'))
    # --- FIM DA CORREÇÃO ---
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'paid_quantity')
    # ### end Alembic commands ###