"""adiciona_crud_clientes_fornecedores_e_melhorias_produto

Revision ID: 82b695a9cb73
Revises: efe50c1f88a0
Create Date: 2025-10-01 09:03:50.614196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82b695a9cb73'
down_revision: Union[str, Sequence[str], None] = 'efe50c1f88a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
