"""adiciona_insumos_e_ficha_tecnica

Revision ID: 8cc5d994868d
Revises: d29d5acaacfe
Create Date: 2025-10-01 09:19:34.496184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cc5d994868d'
down_revision: Union[str, Sequence[str], None] = 'd29d5acaacfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
