"""adiciona_gestao_de_caixa_pdv

Revision ID: 9021d6be7b2d
Revises: 0c22fdaa7599
Create Date: 2025-10-01 08:50:42.369156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9021d6be7b2d'
down_revision: Union[str, Sequence[str], None] = '0c22fdaa7599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_register_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opening_balance', sa.Float(), nullable=False),
    sa.Column('closing_balance', sa.Float(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_register_sessions_is_open'), 'cash_register_sessions', ['is_open'], unique=False)
    op.add_column('sales', sa.Column('cash_register_session_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sales', 'cash_register_sessions', ['cash_register_session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'cash_register_session_id')
    op.drop_index(op.f('ix_cash_register_sessions_is_open'), table_name='cash_register_sessions')
    op.drop_table('cash_register_sessions')
    # ### end Alembic commands ###
