"""Remove self-referencing store_id from Store model

Revision ID: 9eaeec31a7c7
Revises: 579668643d3d
Create Date: 2025-10-16 11:21:26.655550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eaeec31a7c7'
down_revision: Union[str, Sequence[str], None] = '579668643d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('stores_store_id_fkey', 'stores', type_='foreignkey')
    op.drop_column('stores', 'store_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('stores_store_id_fkey', 'stores', 'stores', ['store_id'], ['id'])
    # ### end Alembic commands ###
