"""adiciona_alerta_de_estoque_baixo_em_produtos

Revision ID: a8d19ad88afb
Revises: a77c43829cad
Create Date: 2025-10-07 09:13:23.768494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8d19ad88afb'
down_revision: Union[str, Sequence[str], None] = 'a77c43829cad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('low_stock_threshold', sa.Integer(), server_default='10', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'low_stock_threshold')
    # ### end Alembic commands ###
