"""cria_tabela_transacoes_caixa

Revision ID: cb842ab4b594
Revises: 2269d894faff
Create Date: 2025-10-10 10:25:05.071891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb842ab4b594'
down_revision: Union[str, Sequence[str], None] = '2269d894faff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('pos_x', sa.Integer(), nullable=True))
    op.add_column('tables', sa.Column('pos_y', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'pos_y')
    op.drop_column('tables', 'pos_x')
    # ### end Alembic commands ###
