"""adiciona_insumos_e_ficha_tecnica

Revision ID: d29d5acaacfe
Revises: 308f3ae73049
Create Date: 2025-10-01 09:18:14.736529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd29d5acaacfe'
down_revision: Union[str, Sequence[str], None] = '308f3ae73049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
