"""add position to tables

Revision ID: 3_add_position_to_tables
Revises: 2269d894faff
Create Date: 2025-10-07 11:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3_add_position_to_tables'
down_revision: Union[str, Sequence[str], None] = '2269d894faff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('pos_x', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('tables', sa.Column('pos_y', sa.Integer(), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'pos_y')
    op.drop_column('tables', 'pos_x')
    # ### end Alembic commands ###